name: Linux Release

on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y upx python3-dev libxcb-xinerama0
          
      - name: Build
        run: |
          sed -i "s/v0.0.0/$(git describe --tags)/g" ./main.py
          pip install -r requirements.txt
          pyuic5 -o ui.py main.ui
          pyrcc5 -o resource_rc.py resource.qrc
          pyinstaller --noconsole -F ./main.py --icon icon.png -n cloud-clipboard-go-launcher
          
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/cloud-clipboard-go-launcher
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}