name: macOS Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      version:
        description: '版本号 (例如: v1.0)'
        required: true
        default: 'v4.0'

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Install dependencies
        run: |
          brew update
          brew install create-dmg
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Set Version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION=$(git describe --tags)
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          
      - name: Update Version in Files
        run: |
          sed -i "" "s/v0.0.0/${{ env.VERSION }}/g" ./main.py
          sed -i "" "s/v0.0.0/${{ env.VERSION }}/g" ./setup.py

      - name: Build for x86_64
        run: |
          echo "--- Building for x86_64 ---"
          # 创建一个干净的虚拟环境
          arch -x86_64 python3 -m venv venv_x86_64
          source venv_x86_64/bin/activate
          
          # 在 x86_64 环境中安装依赖
          pip install -r requirements.txt
          pip install py2app
          
          # 生成 UI 文件
          pyuic5 -o ui.py main.ui
          pyrcc5 -o resource_rc.py resource.qrc
          
          # 打包 x86_64 应用
          python setup.py py2app --arch=x86_64
          
          # 退出虚拟环境
          deactivate
          # 重命名输出目录以便区分
          mv dist dist_x86_64

      - name: Build for arm64
        run: |
          echo "--- Building for arm64 ---"
          # 创建一个干净的虚拟环境
          python3 -m venv venv_arm64
          source venv_arm64/bin/activate
          
          # 在 arm64 环境中安装依赖
          pip install -r requirements.txt
          pip install py2app
          
          # 生成 UI 文件
          pyuic5 -o ui.py main.ui
          pyrcc5 -o resource_rc.py resource.qrc
          
          # 打包 arm64 应用
          python setup.py py2app --arch=arm64
          
          # 退出虚拟环境
          deactivate
          # 重命名输出目录以便区分
          mv dist dist_arm64

      - name: Create Universal App
        run: |
          echo "--- Creating Universal App ---"
          # 以 arm64 版本为基础
          cp -R dist_arm64/cloud-clipboard-go.app dist/
          
          # 使用 lipo 合并可执行文件
          lipo -create \
            dist_x86_64/cloud-clipboard-go.app/Contents/MacOS/cloud-clipboard-go \
            dist_arm64/cloud-clipboard-go.app/Contents/MacOS/cloud-clipboard-go \
            -output dist/cloud-clipboard-go.app/Contents/MacOS/cloud-clipboard-go
            
          # 验证合并结果
          lipo -info dist/cloud-clipboard-go.app/Contents/MacOS/cloud-clipboard-go
          
          # 复制 x86_64 的库文件到 arm64 的库目录中
          # rsync -a source/ dest/ 会复制 source 目录的内容到 dest
          echo "--- Merging Frameworks and Libraries ---"
          rsync -av --ignore-existing dist_x86_64/cloud-clipboard-go.app/Contents/Frameworks/ dist/cloud-clipboard-go.app/Contents/Frameworks/
          rsync -av --ignore-existing dist_x86_64/cloud-clipboard-go.app/Contents/Resources/lib/ dist/cloud-clipboard-go.app/Contents/Resources/lib/

      - name: Create DMG
        run: |
          mkdir -p staging
          cp -r "dist/cloud-clipboard-go.app" staging/
          
          create-dmg \
            --volname "cloud-clipboard-go" \
            --volicon "icon.png" \
            --window-pos 200 120 \
            --window-size 600 400 \
            --icon-size 100 \
            --icon "cloud-clipboard-go.app" 175 190 \
            --hide-extension "cloud-clipboard-go.app" \
            --app-drop-link 425 190 \
            "cloud-clipboard-go-${{ env.VERSION }}-macOS-universal.dmg" \
            staging/
            
      - name: Create ZIP backup
        run: |
          cd dist
          zip -r "cloud-clipboard-go-${{ env.VERSION }}-macOS-universal.zip" "cloud-clipboard-go.app"
          cd ..
          
      - name: Calculate SHA256
        id: sha256
        run: |
          DMG_PATH="cloud-clipboard-go-${{ env.VERSION }}-macOS-universal.dmg"
          SHA256=$(shasum -a 256 "$DMG_PATH" | awk '{print $1}')
          echo "sha256_value=$SHA256" >> $GITHUB_OUTPUT

      - name: Store SHA256 for Homebrew Tap
        run: |
          mkdir -p artifact
          echo "${{ steps.sha256.outputs.sha256_value }}" > artifact/sha256.txt
          echo "${{ env.VERSION }}" > artifact/version.txt

      - name: Upload SHA256 and Version
        uses: actions/upload-artifact@v4
        with:
          name: artifact-info
          path: artifact/
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || github.ref_name }}
          files: |
            cloud-clipboard-go-*-universal.dmg
            dist/cloud-clipboard-go-*-universal.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-homebrew-tap:
    name: Update Homebrew Tap
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact-info
          path: ./artifact

      - name: Update Tap Repository
        run: |
          VERSION=$(cat ./artifact/version.txt)
          SHA256=$(cat ./artifact/sha256.txt)

          echo "Updating to version: $VERSION"
          echo "SHA256: $SHA256"

          git clone https://x-access-token:${{ secrets.TAP_TOKEN }}@github.com/jonnyan404/homebrew-tap.git
          cd homebrew-tap

          mkdir -p Casks

          cat ../homebrew/cloud-clipboard-go.rb.template | \
            sed "s/VERSION_PLACEHOLDER/$VERSION/g" | \
            sed "s/SHA256_PLACEHOLDER/$SHA256/g" > \
            Casks/cloud-clipboard-go.rb

          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add Casks/cloud-clipboard-go.rb
          if ! git diff --staged --quiet; then
            git commit -m "Update cloud-clipboard-go to $VERSION"
            git push
          else
            echo "No changes to commit."
          fi
