name: macOS Release

on:
  push:
    tags:
      - '*'
        # 添加手动触发选项
  workflow_dispatch:
    inputs:
      version:
        description: '版本号 (例如: v1.0)'
        required: true
        default: 'v4.0'

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Install dependencies
        run: |
          brew update
          brew install gettext create-dmg
          brew link gettext --force
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Build App
        run: |
          VERSION=$(git describe --tags)
          sed -i "" "s/v0.0.0/$VERSION/g" ./main.py
          sed -i "" "s/v0.0.0/$VERSION/g" ./setup.py
          
          pip install -r requirements.txt
          pip install py2app
          
          # 生成必要的 UI 文件
          pyuic5 -o ui.py main.ui
          pyrcc5 -o resource_rc.py resource.qrc
          
          # 构建 .app 包
          python setup.py py2app
          
      - name: Create DMG
        run: |
          VERSION=$(git describe --tags)
          mkdir -p staging
          cp -r "dist/cloud-clipboard-go.app" staging/
          
          # 创建 DMG 文件
          create-dmg \
            --volname "cloud-clipboard-go" \
            --volicon "icon.png" \
            --window-pos 200 120 \
            --window-size 600 400 \
            --icon-size 100 \
            --icon "cloud-clipboard-go.app" 175 190 \
            --hide-extension "cloud-clipboard-go.app" \
            --app-drop-link 425 190 \
            "cloud-clipboard-go-$VERSION.dmg" \
            staging/
            
      - name: Create ZIP backup
        run: |
          VERSION=$(git describe --tags)
          cd dist
          zip -r "cloud-clipboard-go-$VERSION-macOS.zip" "cloud-clipboard-go.app"
          cd ..
          
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            cloud-clipboard-go-*.dmg
            dist/cloud-clipboard-go-*-macOS.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}